///////////////////////////////////////////////////////////////////////////////////////////////////////
// 
//  
// 
// 
// 
///////////////////////////////////////////////////////////////////////////////////////////////////////

#If Server Or ThickClientOrdinaryApplication Or ExternalConnection Then

#Region Public

#Region ForCallsFromOtherSubsystems

// 

// Returns object details that can be edited
// by processing group changes to details.
//
// Returns:
//  Array of String
//
Function AttributesToEditInBatchProcessing() Export
	
	Result = New Array;
	Result.Add("StartDate");
	Result.Add("EndDate");
	Result.Add("AllowSavingQuestionnaireDraft");
	Result.Add("ShowInQuestionnaireArchive");
	Result.Add("Comment");
	Return Result;
	
EndFunction

// End StandardSubsystems.BatchEditObjects

// 

// Defines a list of report commands.
//
// Parameters:
//  ReportsCommands - See ReportsOptionsOverridable.BeforeAddReportCommands.ReportsCommands
//  Parameters - See ReportsOptionsOverridable.BeforeAddReportCommands.Parameters
//
Procedure AddReportCommands(ReportsCommands, Parameters) Export
	
	If AccessRight("View", Metadata.Reports.PollStatistics) Then
		Command = ReportsCommands.Add();
		Command.Presentation      = NStr("en = 'Survey analysis';");
		Command.MultipleChoice = False;
		Command.FormParameterName  = "Survey";
		Command.WriteMode        = "Write";
		Command.Manager           = "Report.PollStatistics";
	EndIf;
	
EndProcedure

// End StandardSubsystems.ReportsOptions

// 

// Called when preparing message templates and allows you to redefine the list of details and attachments.
//
// Parameters:
//  Attributes - See MessageTemplatesOverridable.OnPrepareMessageTemplate.Attributes
//  Attachments  - See MessageTemplatesOverridable.OnPrepareMessageTemplate.Attachments
//  AdditionalParameters - Structure -  more information about the message template.
//
Procedure OnPrepareMessageTemplate(Attributes, Attachments, AdditionalParameters) Export
	
EndProcedure

// Called when creating messages based on a template to fill in the values of details and attachments.
//
// Parameters:
//  Message - Structure:
//    * AttributesValues - Map of KeyAndValue - :
//      ** Key     - String -  name of the prop in the template;
//      ** Value - String -  the fill value in the template.
//    * CommonAttributesValues - Map of KeyAndValue - :
//      ** Key     - String -  name of the prop in the template;
//      ** Value - String -  the fill value in the template.
//    * Attachments - Map of KeyAndValue:
//      ** Key     - String -  name of the attachment in the template;
//      ** Value - BinaryData
//                  - String - 
//  MessageSubject - AnyRef - 
//  AdditionalParameters - Structure -    additional information about the message template.
//
Procedure OnCreateMessage(Message, MessageSubject, AdditionalParameters) Export
	
EndProcedure

// Fills in the list of SMS recipients when sending a message generated by a template.
//
// Parameters:
//   SMSMessageRecipients - ValueTable:
//     * PhoneNumber - String -  phone number where the SMS message will be sent;
//     * Presentation - String -  representation of the recipient of an SMS message;
//     * Contact       - Arbitrary -  the contact that the phone number belongs to.
//  MessageSubject - AnyRef -  a reference to the object that is the data source.
//                   - Structure  - :
//    * SubjectOf               - AnyRef -  reference to the object that is the data source;
//    * MessageKind - String -  type of generated message: "e-mail" or " SMS Message";
//    * ArbitraryParameters - Map -  filled in list of custom parameters;
//    * SendImmediately - Boolean -  flag for instant sending;
//    * MessageParameters - Structure -  additional message parameters.
//
Procedure OnFillRecipientsPhonesInMessage(SMSMessageRecipients, MessageSubject) Export
	
EndProcedure

// Fills in the list of mail recipients when sending a message generated by a template.
//
// Parameters:
//   EmailRecipients - ValueTable - :
//     * SendingOption - String - 
//     * Address           - String -  e-mail address of the recipient;
//     * Presentation   - String -  representation of the email recipient;
//     * Contact         - Arbitrary -  the contact that the email address belongs to.
//  MessageSubject - AnyRef -  a reference to the object that is the data source.
//                   - Structure  - :
//    * SubjectOf               - AnyRef -  reference to the object that is the data source;
//    * MessageKind - String -  type of generated message: "e-mail" or " SMS Message";
//    * ArbitraryParameters - Map -  filled in list of custom parameters;
//    * SendImmediately - Boolean -  indicates whether the message was sent instantly;
//    * MessageParameters - Structure -  additional message parameters;
//    * ConvertHTMLForFormattedDocument - Boolean -  flag converting the HTML text
//             of a message containing images in the message text due to the features of displaying images
//             in a formatted document;
//    * Account - CatalogRef.EmailAccounts -  account for sending the email.
//
Procedure OnFillRecipientsEmailsInMessage(EmailRecipients, MessageSubject) Export
	
EndProcedure

// End StandardSubsystems.MessageTemplates

#EndRegion

#EndRegion

#EndIf

