///////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2025, OOO 1C-Soft
// All rights reserved. This software and the related materials 
// are licensed under a Creative Commons Attribution 4.0 International license (CC BY 4.0).
// To view the license terms, follow the link:
// https://creativecommons.org/licenses/by/4.0/legalcode
///////////////////////////////////////////////////////////////////////////////////////////////////////
//

#Region Public

// Splits a full name into last name and first name.
// If a custom algorithm that handles local naming rules is implemented in 
// PersonsClientServerLocalization.OnDefineFullNameComponents(), its result is returned. 
// The returned structure follows this algorithm.
// If no custom algorithm is implemented, the standard full name parsing is used.
//
// Parameters:
//  FullName   - String - Source string.
//  NameFormat - String - Specifies the order of name parts in the input string.
//                          Localized implementations may support additional values for this parameter.
//                Default algorithm values::
//                 # "" or "Name,LastName" (first name followed by last name, default)
//                 # "LastName,Name" (last name followed by first name)
//
// Returns:
//  Structure - If no localized algorithm is implemented, contains:
//   * LastName - String - Extracted last name.
//   * Name     - String - The remaining part of the name (first name and middle name, if any).
//       See PersonsClientServerLocalization.OnDefineFullNameComponents.Result
//
// Example:
//   a. NameParts("Ivan Ivanovich Ivanov") returns: 
//      LastName = "Ivanov", Name = "Ivan Ivanovich"
//   b. NameParts("Ivanov Ivan Ivanovich", "LastName,Name") returns: 
//      LastName = "Ivanov", Name = "Ivan Ivanovich"
//   c. NameParts("John Smith") returns: 
//      LastName = "Smith", Name = "John"
//   d. NameParts("John") returns: 
//      LastName = "", Name = "John"
//
Function NameParts(FullName, Val NameFormat = "") Export
	
	Result = New Structure;
	
	PersonsClientServerLocalization.OnDefineFullNameComponents(FullName, NameFormat, Result);
	If ValueIsFilled(Result) Then
		Return Result;
	EndIf;
	
	Result = New Structure;
	Result.Insert("LastName", "");
	Result.Insert("Name", "");

	If Not ValueIsFilled(FullName) Then
		Return Result;
	EndIf;
	
	IsNameComesFirst = NameFormat = "Name,LastName" Or NameFormat = "";
	NameParts = StrSplit(FullName, " ", False); 
	
	If IsNameComesFirst Then
		If NameParts.Count() > 1 Then
			Result.LastName = NameParts[NameParts.UBound()];
			NameParts.Delete(NameParts.UBound());
		EndIf;
	
		Result.Name = StrConcat(NameParts, " ");
	Else
		If NameParts.Count() >= 1 Then
			Result.LastName = NameParts[0];
			NameParts.Delete(0);
		EndIf;
	
		Result.Name = StrConcat(NameParts, " ");
	EndIf;
	
	Return Result;
	
EndFunction

// Generates a short presentation of a person's full name (last name and initials).
// If a custom name generation algorithm is implemented in PersonsClientServerLocalization.OnDefineSurnameAndInitials()
// the function returns the result produced by that algorithm. 
// In this case, the result format and generation rules are defined by the localized procedure.
// If no localized algorithm is implemented or it does not return a value, the default generator is used.
// 
//
// Parameters:
//  FullName          - String, Structure - Person's full name.
//                       A passed string is parsed by NameParts().
//                       A passed structure must contain the LastName and Name fields.
//  FullNameFormat - String - Defines the order in which name components appear in the input.
//                       A localized implementation may support additional formats for this parameter.
//                       The default algorithm supports the following values
//                       :
//                        *  Defines the order in which name components appear in the input.
//                             A localized implementation may support additional formats for this parameter.
//                             The default algorithm supports the following values
//                        * "NameSurname"      - First name followed by last name.
//  IsInitialsComeFirst    - Boolean - Used in the localized algorithm to select the presentation format,
//                       for example, "A. Johns" or "Johns, A". When the default algorithm is used,
//                       the order is determined by the FullNameFormat parameter.
//
// Returns:
//  String - Short form of the name.
//           If the result is generated by a localized procedure, its format is determined by that procedure.
//           If no localized algorithm exists, the default format is returned.
//           :
//            * "LastName" - If no name is provided.
//            * LastName N." or "N. Last Name" if the name is filled in.
//                See PersonsClientServerLocalization.OnDefineSurnameAndInitials.Result
//
// Example:
//  1. InitialsAndLastName("Doe John") -> "Doe J."
//  2. InitialsAndLastName("John Doe", "Name,LastName") -> "J. Doe"
//  3. InitialsAndLastName("Doe") -> "Doe"
//
Function InitialsAndLastName(Val FullName, Val FullNameFormat = "", Val IsInitialsComeFirst = False) Export
	
	Result = "";
	
	PersonsClientServerLocalization.OnDefineSurnameAndInitials(FullName, FullNameFormat, IsInitialsComeFirst, Result);
	If ValueIsFilled(Result) Or Not ValueIsFilled(FullName) Then
		Return Result;
	EndIf;
	
	If TypeOf(FullName) = Type("String") Then
		FullName = NameParts(FullName);
	EndIf;
	
	LastName = FullName.LastName;
	Name = FullName.Name;
	
	If IsBlankString(Name) Then
		Return LastName;
	EndIf;
	
	If FullNameFormat = "Name,LastName" Then
		Template = "%2. %1";
	Else
		Template = "%1 %2.";
	EndIf;
	
	Return StringFunctionsClientServer.SubstituteParametersToString(Template, LastName, Left(Name, 1));
	
EndFunction

#Region ObsoleteProceduresAndFunctions

// Deprecated. Instead, use "StringFunctionsClientServer.IsStringContainsOnlyNationalAlphabetChars".
// 
// The function validates persons' names.
// A name is considered valid if it contains either only national alphabet letters or only Latin letters.
//
// Parameters:
//  LastFirstName - String - A person's name.
//  IsOnlyNationalScriptLetters - Boolean - Flag indicating that valid names should contain only national alphabet letters.
//
// Returns:
//  Boolean - "True" if the name is valid.
//
Function FullNameWrittenCorrectly(Val LastFirstName, IsOnlyNationalScriptLetters = False) Export
	
	CheckResult = True;
	PersonsClientServerLocalization.FullNameWrittenCorrectly(LastFirstName, IsOnlyNationalScriptLetters, CheckResult);
	
	Return CheckResult;
	
EndFunction

#EndRegion

#EndRegion
